DROP TABLE IF EXISTS `chat_message`;
CREATE TABLE `chat_message`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '消息ID',
  `session_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '会话ID',
  `user_id` bigint NULL DEFAULT NULL COMMENT '用户ID',
  `message_type` tinyint NOT NULL COMMENT '消息类型(1:用户,2:AI回复,3:系统,4:客服)',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息内容',
  `intent` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '意图',
  `sentiment` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '情感(positive,neutral,negative,urgent)',
  `is_ai_response` tinyint NULL DEFAULT 0 COMMENT '是否为AI回复(0:否,1:是)',
  `workflow_execution_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '工作流执行ID',
  `sync_status` tinyint NULL DEFAULT 0 COMMENT '同步状态(0:未同步,1:同步中,2:已同步,3:同步失败,4:跳过同步)',
  `sync_time` bigint NULL DEFAULT NULL COMMENT '同步时间',
  `response_time` int NULL DEFAULT NULL COMMENT '响应时间（毫秒）',
  `is_deleted` tinyint NULL DEFAULT 0 COMMENT '是否已删除(0:否,1:是)',
  `metadata` json NULL COMMENT '元数据（JSON格式）',
  `vector_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '向量ID（Milvus）',
  `embedding_status` tinyint NULL DEFAULT 0 COMMENT '向量化状态(0:未向量化,1:已向量化,2:向量化失败)',
  `embedding_time` bigint NULL DEFAULT NULL COMMENT '向量化时间',
  `similarity_score` double NULL DEFAULT NULL COMMENT '相似度分数（用于检索）',
  `create_time` bigint NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_session_id`(`session_id` ASC) USING BTREE,
  INDEX `idx_sync_status`(`sync_status` ASC, `is_deleted` ASC) USING BTREE,
  INDEX `idx_create_time`(`create_time` ASC) USING BTREE,
  INDEX `idx_workflow_exec`(`workflow_execution_id` ASC) USING BTREE,
  INDEX `idx_message_type`(`message_type` ASC) USING BTREE,
  INDEX `idx_is_ai_response`(`is_ai_response` ASC) USING BTREE,
  INDEX `idx_embedding_status`(`embedding_status` ASC) USING BTREE,
  INDEX `idx_intent`(`intent` ASC) USING BTREE,
  INDEX `idx_sentiment`(`sentiment` ASC) USING BTREE,
  INDEX `idx_session_time`(`user_id` ASC, `session_id` ASC, `create_time` ASC) USING BTREE,
  INDEX `idx_user_sync`(`sync_status` ASC, `embedding_status` ASC) USING BTREE,
  INDEX `idx_user_time`(`user_id` ASC, `create_time` DESC) USING BTREE,
  INDEX `idx_session_sync`(`session_id` ASC, `sync_status` ASC, `is_deleted` ASC) USING BTREE,
  INDEX `idx_workflow_exec_deleted`(`workflow_execution_id` ASC, `is_deleted` ASC) USING BTREE,
  INDEX `idx_ai_response_time`(`is_ai_response` ASC, `response_time` ASC, `create_time` DESC) USING BTREE,
  INDEX `idx_intent_sentiment`(`intent` ASC, `sentiment` ASC, `create_time` DESC) USING BTREE,
  FULLTEXT INDEX `ft_content`(`content`)
) ENGINE = InnoDB AUTO_INCREMENT = 267 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '聊天消息表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
