server:
  port: 8032
#  servlet:
#    context-path: /api/mcp-client-demo
#    #大模型对话中文乱码处理
#    encoding:
#      enabled: true
#      force: true
#      charset: utf-8

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mcp-client-demo
  ai:
    # 阿里云百炼配置
    dashscope:
      api-key: ${qwen-api}
      base-url: https://dashscope.aliyuncs.com
#      chat:
#        options:
#          model: qwen-plus
      qwen:
        model: qwen-plus
      deepseek:
        model: deepseek-v3

    # mcp client配置
    mcp:
      client:
        enabled: true
        type: async
        name: mcp-client-demo
        request-timeout: 60s
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:8031

# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn


