server:
  port: 8031
  servlet:
    context-path: /api/mcp-server-demo
    # 大模型对话中文乱码处理
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mcp-server-demo
  ai:
    # 阿里云百炼配置
    dashscope:
      api-key: ${qwen-api}
      base-url: https://dashscope.aliyuncs.com
#      chat:
#        options:
#          model: qwen-plus
      qwen:
        model: qwen-plus
      deepseek:
        model: deepseek-v3

    # mcp server配置
    mcp:
      server:
        enabled: true
        type: sync
        name: mcp-server-demo
        version: 1.0.0
        # SSE 配置
        sse-endpoint: /sse
        sse-message-endpoint: /message

# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn
