server:
  port: 8031
  servlet:
    context-path: /api/mcp-server-demo
    # 大模型对话中文乱码处理
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  application:
    name: mcp-server-demo

  # mysql配置
  datasource:
    url: jdbc:mysql://localhost:3316/rag_demo?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # Druid 连接池配置
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1

  ai:
    # 阿里云百炼配置
    dashscope:
      api-key: ${qwen-api}
      base-url: https://dashscope.aliyuncs.com
#      chat:
#        options:
#          model: qwen-plus
      qwen:
        model: qwen-plus
      deepseek:
        model: deepseek-v3

    # mcp server配置
    mcp:
      server:
        enabled: true
        type: sync
        name: mcp-server-demo
        version: 1.0.0
        # SSE 配置
        sse-endpoint: /sse
        sse-message-endpoint: /message

# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn
